<?php
//Массив для переименования полей в таблице, вместо русских можно ставить любые, если заккоментить элемент он не будет выводиться в таблице

      $headnames["gear_level"]="Уровень предметов";
      $headnames["power"]="ГМ";
      $headnames["level"]="Уровень";
//      $headnames["url"]="Ссылка";
      $headnames["combat_type"]="Тип";
      $headnames["rarity"]="Звёзд";
      $headnames["player"]="Игрок";


//Функция для перевода чисел в *, * в поле $res.= Можно поменять на любой символ
function int_to_star($rarity) {
	$res='';
	for($i=1; $i<=$rarity; $i++) {
		$res.="*";
	}
	return $res;
}

//Тип Боевой единицы, русские названия можно менять
$tip_old=Array("1","2");
$tip_new=Array(".Персонаж.",".Корабль.");

//Функция для перевода Арабских цифр в римские.
function number_to_roman($value)
{
    if($value<0) return "";
    if(!$value) return "0";
    $thousands=(int)($value/1000);
    $value-=$thousands*1000;
    $result=str_repeat("M",$thousands);
    $table=array(
        900=>"CM",500=>"D",400=>"CD",100=>"C",
        90=>"XC",50=>"L",40=>"XL",10=>"X",
        9=>"IX",5=>"V",4=>"IV",1=>"I");
    while($value) {
        foreach($table as $part=>$fragment) if($part<=$value) break;
            $amount=(int)($value/$part);
        $value-=$part*$amount;
        $result.=str_repeat($fragment,$amount);
    }
    return $result;
}

//Функция для изменения имени персонажа из массива перевода.
//Пока пробуем replace


//Массивы перевода персонажей.(все в двух массивах должно быть по порядку!!!)
$hero_eng=Array("GRIEVOUS",
"HUMANTHUG",
"YOUNGLANDO",
"ADMINISTRATORLANDO",
"XWINGRED2",
"PLOKOON",
"ENFYSNEST",
"REY",
"HK47",
"KYLOREN",
"REYJEDITRAINING",
"VISASMARR",
"PHANTOM2",
"RANGETROOPER",
"PAO",
"ARC170REX",
"TIEFIGHTERFOSF",
"CT7567",
"AMILYNHOLDO",
"MAGNAGUARD",
"ROYALGUARD",
"DARTHNIHILUS",
"EWOKELDER",
"OLDBENKENOBI",
"ASAJVENTRESS",
"PRINCESSLEIA",
"LUKESKYWALKER",
"DAKA",
"CC2224",
"ZAMWESELL",
"QUIGONJINN",
"TUSKENSHAMAN",
"HANSOLO",
"TUSKENRAIDER",
"RESISTANCEPILOT",
"GAMORREANGUARD",
"HOTHREBELSOLDIER",
"XWINGBLACKONE",
"JAWASCAVENGER",
"SITHINFILTRATOR",
"BODHIROOK",
"SITHMARAUDER",
"STORMTROOPER",
"SLAVE1",
"CHOPPERS3",
"GEONOSIANSOLDIER",
"UGNAUGHT",
"COMMANDSHUTTLE",
"MOTHERTALZIN",
"PHASMA",
"CADBANE",
"NIGHTSISTERSPIRIT",
"CLONEWARSCHEWBACCA",
"TIEADVANCED",
"AHSOKATANO",
"CHIRRUTIMWE",
"YOUNGHAN",
"FINN",
"ZEBS3",
"COMMANDERLUKESKYWALKER",
"MACEWINDU",
"EWOKSCOUT",
"CHIEFCHIRPA",
"DARTHSIDIOUS",
"HERMITYODA",
"BISTAN",
"CORUSCANTUNDERWORLDPOLICE",
"AAYLASECURA",
"POGGLETHELESSER",
"MAUL",
"ROSETICO",
"LOBOT",
"TIEFIGHTERFIRSTORDER",
"JAWAENGINEER",
"TIEFIGHTERIMPERIAL",
"GEONOSIANSPY",
"SITHTROOPER",
"COUNTDOOKU",
"HOTHLEIA",
"CHIEFNEBIT",
"XWINGRED3",
"CAPITALJEDICRUISER",
"EMPERORPALPATINE",
"SHORETROOPER",
"KYLORENUNMASKED",
"JEDIKNIGHTCONSULAR",
"SITHASSASSIN",
"SMUGGLERCHEWBACCA",
"SCARIFREBEL",
"JEDISTARFIGHTERAHSOKATANO",
"WICKET",
"JEDIKNIGHTGUARDIAN",
"SAVAGEOPRESS",
"HOTHHAN",
"CT210408",
"ANAKINKNIGHT",
"GEONOSIANSTARFIGHTER1",
"JYNERSO",
"L3_37",
"GAUNTLETSTARFIGHTER",
"YOUNGCHEWBACCA",
"SNOWTROOPER",
"JAWA",
"KANANJARRUSS3",
"TIEFIGHTERPILOT",
"URORRURRR",
"ARC170CLONESERGEANT",
"BARRISSOFFEE",
"NIGHTSISTERINITIATE",
"EZRABRIDGERS3",
"DENGAR",
"VEERS",
"RESISTANCETROOPER",
"K2SO",
"FIRSTORDERSPECIALFORCESPILOT",
"EETHKOTH",
"GRANDMOFFTARKIN",
"GHOST",
"UWINGSCARIF",
"TIEREAPER",
"R2D2_LEGENDARY",
"BB8",
"DATHCHA",
"IG88",
"GRANDMASTERYODA",
"UWINGROGUEONE",
"IMAGUNDI",
"XWINGRESISTANCE",
"FIRSTORDERTROOPER",
"MILLENNIUMFALCONPRISTINE",
"NIGHTSISTERZOMBIE",
"MILLENNIUMFALCONEP7",
"FIRSTORDEREXECUTIONER",
"HERASYNDULLAS3",
"HOTHREBELSCOUT",
"LUMINARAUNDULI",
"CAPITALMONCALAMARICRUISER",
"COLONELSTARCK",
"CAPITALSTARDESTROYER",
"BOBAFETT",
"CASSIANANDOR",
"BIGGSDARKLIGHTER",
"JEDISTARFIGHTERCONSULAR",
"BLADEOFDORIN",
"FIRSTORDEROFFICERMALE",
"DIRECTORKRENNIC",
"IG86SENTINELDROID",
"TEEBO",
"GENERALKENOBI",
"FULCRUMAHSOKA",
"ADMIRALACKBAR",
"LOGRAY",
"IMPERIALSUPERCOMMANDO",
"GEONOSIANSTARFIGHTER3",
"GEONOSIANSTARFIGHTER2",
"NUTEGUNRAY",
"NIGHTSISTERACOLYTE",
"SABINEWRENS3",
"SMUGGLERHAN",
"POE",
"MAGMATROOPER",
"TIESILENCER",
"VADER",
"IMPERIALPROBEDROID",
"PAPLOO",
"CLONESERGEANTPHASEI",
"KITFISTO",
"GARSAXON",
"DARTHSION",
"CT5555",
"GREEDO",
"WEDGEANTILLES",
"SUNFAC",
"CAPITALCHIMAERA",
"GRANDADMIRALTHRAWN",
"UMBARANSTARFIGHTER",
"BAZEMALBUS",
"B2SUPERBATTLEDROID",
"DEATHTROOPER",
"TALIA",
"BOSSK",
"FIRSTORDERTIEPILOT",
"QIRA",
"STORMTROOPERHAN",
"WAMPA",
"UNMASKED",
"JEDISTARFIGHTER",
"JEDITRAINING");

$hero_rus=Array("Генерал Гривус",
"Головорез",
"Молодой Лэндо",
"Лэндо Калриссиан",
"Крестокрыл Веджа Антиллеса",
"Пло Кун",
"Энфис Нест",
"Рей ",
"HK-47",
"Кайло Рен",
"Рей (Обучение джедая)",
"Визас Марр",
"Фантом II",
"Дальнобойный штурмовик",
"Пао",
"АИР-170 Рекса",
"СИД-истребитель особого назначения Первого порядка",
"CT-7567 Рекс",
"Эмилин Холдо",
"Магнастраж IG-100",
"Императорская гвардия",
"Дарт Нихилус",
"Эвок-старейшина",
"Оби-Ван Кеноби (Старый Бен)",
"Асажж Вентресс",
"Принцесса Лея",
"Люк Скайуокер (мальчик с фермы)",
"Старая Дака",
"CC-2224 Коди",
"Зам Уэселл",
"Квай-Гон Джинн",
"Таскенский шаман",
"Хан Соло",
"Таскенский рейдер",
"Пилот сопротивления",
"Гаморреанский стражник",
"Солдат повстанцев с Хота",
"Крестокрыл По Дамерона",
"Джава-мусорщик",
"Скимитар",
"Бодхи Рук",
"Ситх-мародер",
"Штурмовик",
"Раб I",
"Чоппер",
"Джеонозийский солдат",
"Угнот",
"Командирский шаттл Кайло Рена",
"Мать Талзин",
"Капитан Фазма",
"Кэд Бэйн",
"Дух Сестры ночи",
"Чубакка (Войны клонов)",
"Усовершенствованный СИД x1",
"Асока Тано",
"Чиррут Имве",
"Молодой Хан Соло",
"Финн",
"Гаразеб Зеб Оррелиос",
"Командир Люк Скайуокер",
"Мейс Винду",
"Эвок-разведчик",
"Вождь Чирпа",
"Дарт Сидиус",
"Отшельник Йода",
"Бистан",
"Полиция Нижнего Корусанта",
"Айла Секура",
"Поггль-младший",
"Дарт Мол",
"Роуз Тико",
"Лобот",
"СИД-истребитель Первого порядка",
"Инженер-джава",
"Имперский СИД-истребитель",
"Джеонозийский шпион",
"Солдат ситхов",
"Граф Дуку",
"Офицер повстанцев Лея Органа",
"Вождь Небит",
"Крестокрыл Биггса Дарклайтера",
"Стойкость",
"Император Палпатин",
"Береговой штурмовик",
"Кайло Рен (без маски)",
"Джедай-консул",
"Ситх-убийца",
"Бывалый контрабандист Чубакка",
"Повстанец-следопыт со Скарифа",
"Джедайский истребитель Асоки Тано",
"Викет",
"Рыцарь-джедай (защитник)",
"Саважж Опресс",
"Капитан Хан Соло",
"CT-21-0408 Эхо",
"Рыцарь-джедай Энакин",
"Джеонозийский истребитель Сан Фака",
"Джин Эрсо",
"L3-37",
"Истребитель Крага",
"Чубакка с Вандора",
"Снежный штурмовик",
"Джава",
"Кэнан Джаррус",
"Пилот СИД-истребителя",
"УроРРуО'Р'Р",
"АИР-170 клона-сержанта",
"Баррисс Оффи",
"Сестра ночи - адепт",
"Эзра Бриджер",
"Денгар",
"Генерал Вирс",
"Солдат сопротивления",
"K-2SO",
"Пилот СИД-истребителя особого назначения Первого порядка",
"Ит Кот",
"Гранд-мофф Таркин",
"Призрак",
"U-крыл Бистана",
"СИД-жнец",
"R2-D2",
"BB-8",
"Дафча",
"IG-88",
"Великий магистр Йода",
"U-крыл Кассиана",
"Има-Ган Ди",
"Крестокрыл Сопротивления",
"Штурмовик Первого порядка",
"Тысячелетний сокол Лэндо",
"Зомби Сестры ночи",
"Тысячелетний сокол (эп. VII)",
"Палач Первого порядка",
"Гера Синдулла",
"Разведчик-повстанец с Хота",
"Луминара Андали",
"Дом-один",
"Полковник Старк",
"Исполнительница",
"Боба Фетт",
"Кассиан Андор",
"Биггс Дарклайтер",
"Истребитель джедая-консула",
"Джедайский истребитель Пло Куна",
"Офицер Первого порядка",
"Директор Кренник",
"Дроид-страж IG-86",
"Тибо",
"Генерал Кеноби",
"Асока Тано (Фалкрам)",
"Адмирал Акбар",
"Логрэй",
"Имперский суперкоммандос",
"Истребитель джеонозийского шпиона",
"Истребитель джеонозийского солдата",
"Нут Ганрей",
"Сестра ночи - послушница",
"Сабин Врен",
"Бывалый контрабандист Хан Соло",
"По Дамерон",
"Магма-штурмовик",
"СИД-истребитель Глушитель",
"Дарт Вейдер",
"Имперский разведывательный дроид",
"Паплу",
"Клон-сержант (фаза I)",
"Кит Фисто",
"Гар Саксон",
"Дарт Сион",
"CT-5555 Файвз",
"Гридо",
"Ведж Антиллес",
"Сан Фак",
"Химера",
"Гранд-адмирал Траун",
"Умбарский звездный истребитель",
"Бэйз Мальбус",
"Боевой супер-дроид B2",
"Штурмовик смерти",
"Талья",
"Босск",
"Пилот СИД-истребителя Первого порядка",
"Ки'ра",
"Штурмовик Хан",
"Вампа",
" Без маски",
"Джедайский истребитель ",
"(Обучение джедая)");
?>